package com.yunfan.trainproject.model.entity;

import java.util.Set;

import com.yunfan.mdk.model.entity.BModel;

// Generated 2016-3-25 10:49:59 by Hibernate Tools 3.4.0.CR1

/**
 * Compony generated by hbm2java
 */
public class Compony extends BModel implements java.io.Serializable {

	private String componyName;
	private String area;
	private String department;
	private String deptGroup;
	private Integer femaleStaffNumber;
	private Integer maleStaffNumber;
	
	private Set<NaviTree> children;
	
	private Dictionary deptDic;
	private Dictionary groupDic;

	public Compony() {
	}

	public Compony(int id) {
		this.setId(id);
	}

	public Compony(int id, String componyName, String area, String department,
			String deptGroup, Integer femaleStaffNumber, Integer maleStaffNumber) {
		this.setId(id);
		this.componyName = componyName;
		this.area = area;
		this.department = department;
		this.deptGroup = deptGroup;
		this.femaleStaffNumber = femaleStaffNumber;
		this.maleStaffNumber = maleStaffNumber;
	}

	public String getComponyName() {
		return this.componyName;
	}

	public void setComponyName(String componyName) {
		this.componyName = componyName;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public Integer getFemaleStaffNumber() {
		return this.femaleStaffNumber;
	}

	public void setFemaleStaffNumber(Integer femaleStaffNumber) {
		this.femaleStaffNumber = femaleStaffNumber;
	}

	public Integer getMaleStaffNumber() {
		return this.maleStaffNumber;
	}

	public void setMaleStaffNumber(Integer maleStaffNumber) {
		this.maleStaffNumber = maleStaffNumber;
	}

	public Dictionary getDeptDic() {
		return deptDic;
	}

	public void setDeptDic(Dictionary deptDic) {
		this.deptDic = deptDic;
	}

	public Dictionary getGroupDic() {
		return groupDic;
	}

	public void setGroupDic(Dictionary groupDic) {
		this.groupDic = groupDic;
	}

	public String getDeptGroup() {
		return deptGroup;
	}

	public void setDeptGroup(String deptGroup) {
		this.deptGroup = deptGroup;
	}

	public Set<NaviTree> getChildren() {
		return children;
	}

	public void setChildren(Set<NaviTree> children) {
		this.children = children;
	}

}
